INSERT INTO tasks (title, description, status, priority, user_id, created_at, updated_at) VALUES
('프로젝트 기획서 작성', '2024년 신규 프로젝트 기획서 초안 작성', 'PENDING', 'HIGH', 1, NOW(), NOW()),
('API 문서 정리', 'REST API 엔드포인트 문서화', 'IN_PROGRESS', 'MEDIUM', 1, NOW(), NOW()),
('버그 수정 #101', '로그인 시 토큰 만료 이슈 해결', 'COMPLETED', 'URGENT', 1, NOW(), NOW()),
('UI 디자인 리뷰', '메인 페이지 디자인 검토', 'PENDING', 'LOW', 1, NOW(), NOW()),
('데이터베이스 마이그레이션', 'PostgreSQL 15 업그레이드', 'IN_PROGRESS', 'HIGH', 1, NOW(), NOW()),
('테스트 코드 작성', '유닛 테스트 커버리지 80% 달성', 'PENDING', 'MEDIUM', 1, NOW(), NOW()),
('코드 리팩토링', '레거시 코드 정리', 'CANCELLED', 'LOW', 1, NOW(), NOW()),
('보안 점검', '취약점 스캔 및 패치', 'COMPLETED', 'URGENT', 1, NOW(), NOW()),
('성능 최적화', '쿼리 튜닝 및 캐싱 적용', 'IN_PROGRESS', 'HIGH', 1, NOW(), NOW()),
('배포 자동화', 'CI/CD 파이프라인 구축', 'PENDING', 'MEDIUM', 1, NOW(), NOW()),
('사용자 피드백 분석', '설문조사 결과 정리', 'COMPLETED', 'LOW', 1, NOW(), NOW()),
('모바일 대응', '반응형 웹 디자인 적용', 'IN_PROGRESS', 'HIGH', 1, NOW(), NOW()),
('로그 모니터링 설정', 'ELK 스택 구성', 'PENDING', 'MEDIUM', 1, NOW(), NOW()),
('백업 정책 수립', '일일 자동 백업 설정', 'COMPLETED', 'HIGH', 1, NOW(), NOW()),
('신규 기능 개발', '대시보드 위젯 추가', 'IN_PROGRESS', 'URGENT', 1, NOW(), NOW()),
('문서 번역', '영문 매뉴얼 한글화', 'PENDING', 'LOW', 1, NOW(), NOW()),
('인증 시스템 개선', 'OAuth2.0 소셜 로그인 추가', 'CANCELLED', 'MEDIUM', 1, NOW(), NOW()),
('에러 핸들링 개선', '글로벌 예외 처리 정리', 'COMPLETED', 'MEDIUM', 1, NOW(), NOW()),
('캐시 서버 구축', 'Redis 클러스터 설정', 'PENDING', 'HIGH', 1, NOW(), NOW()),
('코드 리뷰 가이드 작성', '팀 코딩 컨벤션 정리', 'IN_PROGRESS', 'LOW', 1, NOW(), NOW());
